### ISSUE TITLE
Resource directory not created

### ISSUE THREAD

**Issue by mnadareski** [meepingsnesroms/libretro-palmm515emu#4]
The required resource directory `QDir::homePath() + "/Mu"` does not seem to be automatically created on first run, instead it throws a generic "emulation error 4".

**System info:**

```
Ubuntu MATE x64 18.04
Qt Creator 4.7.0
Based on Qt 5.11.1 (GCC 5.3.1 20160406 (Red Hat 5.3.1-6), 64 bit)
Built on Jul 17 2018 04:23:40
From revision dedbb40f57
```

**Comment by meepingsnesroms** [comment]
You need [this](https://github.com/meepingsnesroms/libretro-palmm515emu/blob/master/palmRoms/Palm%20m515/rom(selfDumped).bin) ROM from renamed to "palmos41-en-m515.rom" put in the resource directory for the "emulation error 4".

I just fixed "push up to touch the screen", directory creation and case sensitivity, can you test it again?

**Comment by mnadareski** [comment]
I was using that rom (renamed) as it was the one I could get going. As for the directory creation, it still doesn't seem to make the folder, in my case `~/Mu`, either when the emulator is first booted or when emulation is attempted to be started.

**Comment by meepingsnesroms** [comment]
Try now, before I only checked on first launch and recompiling from Qt keeps old setting from the last launch so your directory was already set.

**Comment by mnadareski** [comment]
Confirmed that this now auto-generates the directory. Also now lets me take screenshots properly.
